dist: focal

language: python
python:
  - "3.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gnupg
      - zip
      - wget
      - pkg-config

install:
  - pip install -r requirements_dev.txt


before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.2.0/bazel_3.2.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_3.2.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_3.2.0-linux-x86_64.deb

script:
  - /usr/bin/bazel --bazelrc=.bazelrc.travis test //...
  - make build
  - make test
  - make lint
