reorder_imports = true
match_block_trailing_comma = false
newline_style = 'Unix'
use_field_init_shorthand = true

# nigntly

#imports_granularity = 'Module'
#group_imports = 'StdExternalCrate'
#imports_layout = "HorizontalVertical"
#force_multiline_blocks = true
#trailing_comma = 'Always'
