name: install
on:
  - push
  - pull_request
jobs:
  install-from-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          # The oldest supported python version
          python-version: 3.7
      - run: python -m pip install .
      - run: |
          bean-check --help
          bean-doctor --help
          bean-example --help
          bean-format --help
  install-from-sources-oldstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          # The oldest supported python version
          python-version: 3.7
      - run: python setup.py install
      - run: |
          bean-check --help
          bean-doctor --help
          bean-example --help
          bean-format --help
  install-from-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          # The oldest supported python version
          python-version: 3.7
      - rum: python -m pip install build
      - run: python -m build --sdist
      - run: python -m pip install dist/beancount-*.zip
      - run: |
          bean-check --help
          bean-doctor --help
          bean-example --help
          bean-format --help
